services:
  - type: web
    name: sylverith-school-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
